### ISSUE TITLE
PA review: choose a task

### ISSUE THREAD

**Issue by victorwu3** [victorwu3/Taskable#12]

**Comment by victorwu3** [comment]
made a form page for users to input their information to search for tutors. 
From the splash page, users can pick one of the featured task buttons and it will automatically fill in the subject field in the form. they can change it thru the dropdown there.

-updated the error message styling on signup/login. keeping the temp. logout button up top until i build the dashboard page. ill throw that together today

I also have a quick question about styling - it seems some things are slightly slightly off on Heroku and doesn't look as nice. Don't know if its just my computer

**Comment by AM-Harris** [comment]
I haven't seen what it looks like on your computer, but styling looks good to me on heroku

- [x]  When I log in, I am redirected to dashboard, and from there I have no way to get to this page where I fill out the tutor form
- [x] When I test the form from a logged out state I get 404 not found
- [x] When I test the form from a logged in state I get: GET https://taskable.herokuapp.com/api/subjects/1/tutors_for_hires/?currentSubject=1&address=asdfasdsdfasdf&ed_lvl=3&description=asdfasdfasd 404 (Not Found)

**Comment by victorwu3** [comment]
Just updated my dashboard to have some more useful information with a simple greeting, and style image-links that take you to the form. 
I think those errors from testing the form is coming from no data in the database yet. It's querying available tutors for a certain subject, but there are none in the heroku database right now

**Comment by AM-Harris** [comment]
The updates look good! 

- [x]  Adequate seeds to demonstrate the feature

**Comment by victorwu3** [comment]
Just updated my app. Seeded a bunch of info and the form is fully working now. if you fill out the form and click submit, if you inspect the next page you should see the available tutors for hire in the state under tutors-tutors

**Comment by AM-Harris** [comment]
Did you reseed on heroku? I didn't see it

**Comment by victorwu3** [comment]
they seem to be working on my computer on heroku if you want to come look at it. i still need to implement an error handler for if you dont fill out every part of the form, but other than that, it should be working

**Comment by AM-Harris** [comment]
Hmmm, I'm not getting any errors, I just don't see any tutors listed when I submit the form. I've tried a couple different search criteria, and I never get a list of tutors. It's just blank. I do see from logger that state is populated with tutors though

**Comment by victorwu3** [comment]
that may be from either not filling the form out completely or a certain combination I didnt account for in my seeds but I think i covered them all, if not most

**Comment by victorwu3** [comment]
updated my form page with errors. if you dont fill out all fields, errors come up and won't take you to the show page unless you do. 
show page should receive the available tutors in the state, and i stored it in local storage so if you refresh on the show page the tutors are still available

**Comment by AM-Harris** [comment]
Looks good to me!
