### ISSUE TITLE
PA Review: user auth

### ISSUE THREAD

**Issue by victorwu3** [victorwu3/Taskable#9]

**Comment by AM-Harris** [comment]
Functionality:

- [x] Remove login and sign up buttons when logged in
- [x] error functionality is really cool, nice!
- [x] Even though it isn't in the real task rabbit. You should be able to switch back to the login page from the sign up page and vice versa, and also go back to the landing page.  

Styling:
- [x] logout button needs to be styled
- [x] errors should be that golden yellow color like the real task rabbit. 
- [x] overall styling is awesome!

**Comment by victorwu3** [comment]
Got it. I’m planning on having a redirect to a different dashboard/index page when user is logged in, not to the main splash page setup now so I’ll have signout buttons there. For that reason, that’s why I have a temporary unstyled signout button just at the top. I’ll be sure to implement the switching between login and sign up. Also, was saving the styling of the errors for later but I’ll get that done. Thanks for the feedback!

Victor

**Comment by AM-Harris** [comment]
Looks really really nice. Thanks, Victor!
